# Локальная разработка: http://localhost:8080
server {
    listen 8080;
    server_name localhost;

    root /root/bajikovasite;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэш отключён для разработки
    add_header Cache-Control "no-store";
}
